site_name: ZTL's Blog
theme:
  name: material
  font:
    text: Noto Sans
    code: Fira Code
  icon:
    logo: material/alpha-z-box
  favicon: assets/icon.jpg
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - def_list
  - footnotes
  - meta
  - toc
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed

nav:
  - Home: home.md
  - Blogs:
    - 题解:
      - BZOJ3028 食物: BZOJ3028_food/main.md
      - HNOI2015 亚瑟王: HNOI2015_YaSeWang/main.md
    - 算法:
      - 细说最短路: SP/main.md
    - 数据结构:
      - 树状数组: BIT/main.md
    - 模板:
      - 替罪羊树: template/tzy_tree.md
      - 后缀自动机: template/sam.md
      - 马拉车: template/manacher.md
      - AC 自动机: template/ac.md
    - 具体数学:
      - 0：前言: concrete_maths/0.md
      - 1：递归式与封闭式: concrete_maths/1.md
      - 2：和式与封闭式: concrete_maths/2.md
    - 其他:
      - powerlevel10k: P10k/main.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: github.com/zhangtianli2006/

copyright: Copyright &copy; 2021 Tianli Zhang

extra_css:
  - static/css/extra.css

extra_javascript:
  - "https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-MML-AM_CHTML"
